
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678a

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis_config.xml